# Generated by Django 5.1.2 on 2024-11-13 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_brand_and_charging_time_in_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='charging_time',
        ),
    ]
